CREATE TABLE public.raw_people_influencers (
    record_id                text PRIMARY KEY,
    record_type              text NOT NULL,
    full_name                text,
    preferred_name           text,
    gender                   text,
    birth_date               date,
    email                    text,
    phone                    text,
    city                     text,
    country                  text,
    occupation               text,
    influencer_category      text,
    primary_platform         text,
    followers_count          bigint,
    total_followers_count    bigint,
    engagement_rate          numeric(6,3),
    engagement_rate_tier     text,
    interests                text,
    notes                    text,
    secondary_platform       text,
    secondary_followers_count bigint,
    average_monthly_reach    bigint,
    collaboration_status     text,
    languages                text,
    portfolio_url            text,
    last_contact_date        date
);